version: '3.9'

services:
  nfs-server:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host                  # Use host networking
    volumes:
      - jobfile-run:/jobfile-run        # Exported directory
      - ./secrets:/etc/secrets:ro       # Secrets for users
      - /var/lib/nfs:/var/lib/nfs       # Host NFS state
      - /etc/exports:/etc/exports       # Host exports file
      
    privileged: true                    # Required for NFS kernel access

    secrets:
      - nfs_users

secrets:
  nfs_users:
    file: ./secrets/nfs_users

volumes:
  jobfile-run:




  # nfs-client:
  #   image: debian:latest
  #   depends_on:
  #     - nfs-server
  #   command: >
  #     bash -c "
  #     apt-get update && apt-get install -y nfs-common &&
  #     mkdir -p /mnt/jobfiles &&
  #     mount -o vers=4,nolock nfs-server:/jobfile-run /mnt/jobfiles &&
  #     ls /mnt/jobfiles
  #     "





# version: '3.8'

# services:
#   nfs-server:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: nfs-server
#     volumes:
#       - /mnt/nfs:/mnt/nfs
#       - ./secrets:/etc/secrets
#       - /jobfile-run:/jobfile-run
#     ports:
#       - "2049:2049"  # NFS port
#     networks:
#       - mynetwork
#     restart: always

#   # Other services that require NFS mount
#   service1:
#     image: your-image1
#     volumes:
#       - nfs-server:/jobfile-run
#     networks:
#       - mynetwork

#   service2:
#     image: your-image2
#     volumes:
#       - nfs-server:/jobfile-run
#     networks:
#       - mynetwork

# networks:
#   mynetwork:
#     driver: bridge

# volumes:
#   nfs-server:
#     driver: local



# version: '3.8'

# services:
#   nfs-server:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - nfs-data:/jobfile-run
#     secrets:
#       - users.txt
#     networks:
#       - nfs-network

# volumes:
#   nfs-data:
#     driver: local

# secrets:
#   users.txt:
#     file: secrets/users.txt

# networks:
#   nfs-network:
#     driver: bridge